spring:
  datasource:
    url: jdbc:postgresql://172.17.205.29:5432/compounds_cmm_db
    username: alejandra
    password: alejandra*
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
