spring:
  datasource:
    url: jdbc:postgresql://172.17.205.29:5432/compounds_cmm_db
    username: alejandra
    password: alejandra*
    driver-class-name: org.postgresql.Driver
    initialization-mode: always  # Ensure the datasource is always initialized

  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    root: DEBUG
    com.example.myapp: DEBUG
    org.springframework.jdbc.core: DEBUG

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:mykeystore.jks  # Keystore located in src/main/resources
    key-store-password: alejandra       # The password of the keystore
    key-store-type: JKS                  # Keystore type
    key-alias: cmm-backend              # Alias for the key inside the keystore